name: enem_app
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  equatable: ^2.0.5
  dio: ^5.6.0
  get_it: ^7.7.0
  internet_connection_checker: ^2.0.0
  multiple_result: ^5.1.0
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.10+1
  shimmer: ^3.0.0
  provider: ^6.1.2
  shared_preferences: ^2.3.2
  flutter_native_splash: ^2.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  icons_launcher: ^2.1.7

flutter:

  uses-material-design: true
  assets:
    - assets/

icons_launcher:
  image_path: "assets/enem_logo.png"
  platforms:
    android: 
      image_path: "assets/enem_logo.png"
      enable: true
      adaptive_background_color: "#140000"
      adaptive_foreground_image: "assets/enem_logo.png"
    ios:
      enable: true
      image_path: "assets/enem_logo.png"